"""add_tenant_account_management_fields

Revision ID: 8cdb0a4df7aa
Revises: 01b49a4d2395
Create Date: 2026-05-29 19:08:06.266587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdb0a4df7aa'
down_revision: Union[str, Sequence[str], None] = '01b49a4d2395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tenants', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('tenants', sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('password_change_code', sa.String(length=64), nullable=True))
    op.add_column('tenants', sa.Column('password_change_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'password_change_code_expires_at')
    op.drop_column('tenants', 'password_change_code')
    op.drop_column('tenants', 'verification_code_expires_at')
    op.drop_column('tenants', 'verification_code')
    op.drop_column('tenants', 'is_verified')
    # ### end Alembic commands ###
