"""add owner credentials and db_url to tenants

Revision ID: 9d5aafb163fa
Revises: 29c8ce645990
Create Date: 2026-05-25 01:10:57.847668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5aafb163fa'
down_revision: Union[str, Sequence[str], None] = '29c8ce645990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('owner_email', sa.String(length=255), nullable=False))
    op.add_column('tenants', sa.Column('owner_password_hash', sa.String(length=255), nullable=False))
    op.add_column('tenants', sa.Column('db_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_tenants_owner_email'), 'tenants', ['owner_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_owner_email'), table_name='tenants')
    op.drop_column('tenants', 'db_url')
    op.drop_column('tenants', 'owner_password_hash')
    op.drop_column('tenants', 'owner_email')
    # ### end Alembic commands ###
